### ISSUE TITLE
ortro installation..

### ISSUE THREAD

**Issue by emb3dd3d** [lucor/ortro#1]
Greets.. I was looking for an install doc but haven't found anything. so I figured I would just launch and hopefully follow the screen.  I get to the pre-installation check and trying to find ssh.  I typed in the path but there is no save or continue button.  I am hoping this is something simple.  My host is a Centos 6.3 box with php5.3.x.  LMK if there is something i am missing.

Thanx

**Comment by lucor** [comment]
Please check the path has the trailing slash (i.e. /usr/local/bin/ )

**Comment by emb3dd3d** [comment]
yes I have tried it several times.. but had to jump on another urgent
project. I will give it another go today.. here is What I get..

Thanks for responding.. I wasn't sure where to look for assistance with
this.
